"""
shield_query.py
===============
Runtime interface to the PRISM model checker.

This module is responsible for:
  1. Launching PRISM as a subprocess (or connecting to a PRISM server).
  2. Querying pre-computed probability tables for (state, action) pairs.
  3. Returning the probability that a given action leads to a safety violation.

Two modes are supported:
  - OFFLINE TABLE MODE (default): Pre-computed probability tables are loaded
    from disk. Zero subprocess overhead at runtime. Tables must be generated
    offline via `prism debris_capture.pm properties.pctl -exportresults`.
  - ONLINE PRISM MODE: PRISM is invoked as a subprocess for each query.
    High latency (~100ms per call), suitable only for offline analysis.

Usage
-----
>>> query = PRISMShieldQuery.from_table("shield/prism_models/p_collision_table.npy")
>>> p_collision = query.collision_prob(abstract_state, action=0)
>>> is_safe = query.is_safe(abstract_state, action=0, threshold=0.05)
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Dict, List, Optional, Union

import numpy as np

from .abstraction import AbstractState, StateAbstraction

logger = logging.getLogger(__name__)

# PRISM action index constants (must match debris_capture.pm)
ACTION_APPROACH = 0
ACTION_HOLD     = 1
ACTION_RETREAT  = 2


# ─────────────────────────────────────────────────────────────────────────────
# Pre-computed probability table helper
# ─────────────────────────────────────────────────────────────────────────────

class ProbabilityTable:
    """
    Wraps a pre-computed (num_states, num_actions) numpy array of safety
    probabilities generated by PRISM.

    Table shape: (45, 3)
      rows    → abstract state index  (0..44, via StateAbstraction.state_to_index)
      columns → action               (0=approach, 1=hold, 2=retreat)
      values  → P(collision within N steps | state, action)
    """

    NUM_STATES  = 45
    NUM_ACTIONS = 3

    def __init__(self, table: np.ndarray):
        assert table.shape == (self.NUM_STATES, self.NUM_ACTIONS), (
            f"Expected table shape ({self.NUM_STATES}, {self.NUM_ACTIONS}), "
            f"got {table.shape}"
        )
        self._table = table
        self._abstraction = StateAbstraction()

    @classmethod
    def from_file(cls, path: Union[str, Path]) -> "ProbabilityTable":
        table = np.load(str(path))
        return cls(table)

    @classmethod
    def uniform_safe(cls) -> "ProbabilityTable":
        """Create a placeholder table with all zeros (always safe). For testing."""
        return cls(np.zeros((cls.NUM_STATES, cls.NUM_ACTIONS)))

    def query(self, state: AbstractState, action: int) -> float:
        """Return P(collision | state, action)."""
        idx = self._abstraction.state_to_index(state)
        return float(self._table[idx, action])

    def safest_action(self, state: AbstractState) -> int:
        """Return the action with the lowest collision probability."""
        idx = self._abstraction.state_to_index(state)
        return int(np.argmin(self._table[idx, :]))


# ─────────────────────────────────────────────────────────────────────────────
# PRISM query interface
# ─────────────────────────────────────────────────────────────────────────────

class PRISMShieldQuery:
    """
    Runtime shield query engine.

    In production (Isaac Lab training), use the offline table mode for
    minimal latency. Use online PRISM mode for model validation and
    generating the pre-computed tables.

    Parameters
    ----------
    mode : str
        'table' (default) or 'online'.
    table : ProbabilityTable | None
        Pre-computed probability table (required for 'table' mode).
    prism_executable : str
        Path to the PRISM binary (required for 'online' mode).
    model_path : str
        Path to the .pm PRISM model file (required for 'online' mode).
    safety_threshold : float
        Maximum allowable collision probability (default 0.05 = 5%).
    """

    def __init__(
        self,
        mode: str = "table",
        table: Optional[ProbabilityTable] = None,
        prism_executable: str = "prism",
        model_path: str = "shield/prism_models/debris_capture.pm",
        safety_threshold: float = 0.05,
    ):
        self.mode = mode
        self.safety_threshold = safety_threshold
        self._abstraction = StateAbstraction()

        if mode == "table":
            if table is None:
                logger.warning(
                    "No probability table provided — using all-safe placeholder. "
                    "Generate a real table with generate_table()."
                )
                table = ProbabilityTable.uniform_safe()
            self._table = table
        elif mode == "online":
            self._prism_bin  = prism_executable
            self._model_path = model_path
            self._check_prism()
        else:
            raise ValueError(f"Unknown mode: {mode!r}. Choose 'table' or 'online'.")

    # ── Factory constructors ─────────────────────────────────────────────────

    @classmethod
    def from_table(
        cls,
        table_path: Union[str, Path],
        safety_threshold: float = 0.05,
    ) -> "PRISMShieldQuery":
        table = ProbabilityTable.from_file(table_path)
        return cls(mode="table", table=table, safety_threshold=safety_threshold)

    @classmethod
    def from_prism(
        cls,
        prism_executable: str,
        model_path: str,
        safety_threshold: float = 0.05,
    ) -> "PRISMShieldQuery":
        return cls(
            mode="online",
            prism_executable=prism_executable,
            model_path=model_path,
            safety_threshold=safety_threshold,
        )

    # ── Main query API ───────────────────────────────────────────────────────

    def collision_prob(
        self,
        abstract_state: AbstractState,
        action: int,
    ) -> float:
        """
        Return P(collision within N steps | abstract_state, action).

        Parameters
        ----------
        abstract_state : AbstractState
        action         : int  (0=approach, 1=hold, 2=retreat)

        Returns
        -------
        float in [0, 1]
        """
        if self.mode == "table":
            return self._table.query(abstract_state, action)
        else:
            return self._online_query(abstract_state, action)

    def is_safe(
        self,
        abstract_state: AbstractState,
        action: int,
    ) -> bool:
        """Return True iff P(collision | state, action) ≤ safety_threshold."""
        return self.collision_prob(abstract_state, action) <= self.safety_threshold

    def safe_action_set(self, abstract_state: AbstractState) -> List[int]:
        """Return list of actions whose collision probability is within threshold."""
        return [
            a for a in range(3)
            if self.is_safe(abstract_state, a)
        ]

    def safest_action(self, abstract_state: AbstractState) -> int:
        """Return the single action with minimum collision probability."""
        if self.mode == "table":
            return self._table.safest_action(abstract_state)
        probs = [self.collision_prob(abstract_state, a) for a in range(3)]
        return int(np.argmin(probs))

    # ── Offline table generation ─────────────────────────────────────────────

    def generate_table(self, output_path: Union[str, Path]) -> np.ndarray:
        """
        Generate the full (45, 3) probability table by querying PRISM for
        every (state, action) combination.

        This is an OFFLINE operation run once; the result is saved to disk
        and loaded at runtime via ProbabilityTable.from_file().

        Requires PRISM to be installed and the model_path set.

        Parameters
        ----------
        output_path : str | Path
            Where to save the resulting .npy file.

        Returns
        -------
        table : np.ndarray  (45, 3)
        """
        if self.mode != "online":
            raise RuntimeError("generate_table() requires mode='online'.")

        abstraction = StateAbstraction()
        table = np.zeros((ProbabilityTable.NUM_STATES, ProbabilityTable.NUM_ACTIONS))

        for idx in range(ProbabilityTable.NUM_STATES):
            state = abstraction.index_to_state(idx)
            for action in range(ProbabilityTable.NUM_ACTIONS):
                p = self._online_query(state, action)
                table[idx, action] = p
                logger.debug(f"State {idx:2d} Action {action}: P(collision)={p:.4f}")

        np.save(str(output_path), table)
        logger.info(f"Probability table saved to {output_path}")
        return table

    # ── Online PRISM subprocess ───────────────────────────────────────────────

    def _online_query(self, state: AbstractState, action: int) -> float:
        """
        Query PRISM for P(collision | state, action) using subprocess.

        Writes a temporary properties file targeting the initial state
        and parses the scalar result from PRISM stdout.
        """
        action_map = {0: "approach", 1: "hold", 2: "retreat"}
        action_label = action_map[action]

        # Build PRISM property string that fixes the initial state
        # by using conditional reachability with state constraints
        prop = f'P=? [ F<=20 "collision" ]'

        # PRISM initial state override via -const flags
        const_args = [
            "-const", f"d={state.d}",
            "-const", f"f={state.f}",
            "-const", f"t={state.t}",
        ]

        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".pctl", delete=False
        ) as pf:
            pf.write(prop + "\n")
            prop_file = pf.name

        try:
            cmd = [
                self._prism_bin,
                self._model_path,
                prop_file,
                *const_args,
                "-javamaxmem", "2g",
                "-cuddmaxmem", "1g",
            ]
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=30,
            )
            return self._parse_prism_result(result.stdout)
        except subprocess.TimeoutExpired:
            logger.error("PRISM query timed out. Returning conservative p=1.0.")
            return 1.0
        finally:
            os.unlink(prop_file)

    @staticmethod
    def _parse_prism_result(stdout: str) -> float:
        """Parse the probability value from PRISM stdout."""
        for line in stdout.splitlines():
            line = line.strip()
            if line.startswith("Result:"):
                parts = line.split(":")
                try:
                    return float(parts[-1].strip().split()[0])
                except (ValueError, IndexError):
                    pass
        logger.warning("Could not parse PRISM result. Returning conservative p=1.0.")
        return 1.0

    def _check_prism(self):
        """Verify that PRISM is available on PATH."""
        try:
            result = subprocess.run(
                [self._prism_bin, "-version"],
                capture_output=True, text=True, timeout=5
            )
            logger.info(f"PRISM found: {result.stdout.strip()}")
        except (FileNotFoundError, subprocess.TimeoutExpired):
            raise RuntimeError(
                f"PRISM executable not found at '{self._prism_bin}'. "
                "Download from https://www.prismmodelchecker.org/ and add to PATH."
            )
